### ISSUE TITLE
Asking for creating a function graph of TacO

### ISSUE THREAD

**Issue by anolting** [BoyC/GW2TacO#12]
Hi @BoyC 

I'm on the way to file a request at wine.hq or respectively asking to reopen an older issue within the dxvk project (https://github.com/doitsujin/dxvk/issues/1225) to support d3d11 swapchain. 
A contributor of dxvk ask me to get in touch with you to ask if there is chance to get a function graph (a path to the d3d11 and dxgi dlls it uses internally)  of your addon showing how this addon integrates into and work with GW2 ?
I'm not a programmer but willing to offer other support probably needed.
Best Alex

**Comment by BoyC** [comment]
Well the source code is here, they're free to examine it, should speak volumes. The CCoreDX11Device::InitAPI and CCoreDX11Device::CreateDirectCompositionSwapchain functions are a good start.

**Comment by coderedart** [comment]
Maybe I am wrong, but from what I understand.
Taco does not use DLL injection method. It runs as a completely sepearate app that just asks windows where gw2 window is, and resizes/places itself over gw2 window with transparency/letting my use passthrough. That is why taco is very safe.

I think you are looking for add-ons like arcdps, addon loader or radial mount. They use the DLL injection method. Come join them at https://discord.gg/zqeHCEg where you can ask the gw2dev community.

**Comment by BoyC** [comment]
> Maybe I am wrong, but from what I understand. @anolting
> Taco does not use DLL injection method. It runs as a completely sepearate app that just asks windows where gw2 window is, and resizes/places itself over gw2 window with transparency/letting my use passthrough. That is why taco is very safe.

While that is true, WINE doesn't support much of what's needed to achieve that, and it's up to the WINE devs to fix those issues for which TacO is a good template. (WINE support has been a looooong standing feature request to which my answer always was that it's their responsibility - seems like someone is finally taking a look)

**Comment by coderedart** [comment]
oh sorry. i immediately assumed that they were trying to make taco integrate directly with the dll injection. i hear taco and my mind immediately jumps to https://www.reddit.com/r/Guildwars2/comments/mz0sar/taco_gw2_taco_going_open_source/gw1a7ee/ . it really is nice that someone is looking into wine support finally.

**Comment by anolting** [comment]
Hi BoyC 
this issue/discussion can be closed.
Best Alex
