### ISSUE TITLE
DX11 beta uses a different window class name.

### ISSUE THREAD

**Issue by dlamkins** [BoyC/GW2TacO#13]
https://github.com/BoyC/GW2TacO/blob/a10c305105a2a81cd15c443e2c00a6fda8355231/gw2pois.cpp#L744

https://github.com/BoyC/GW2TacO/blob/a10c305105a2a81cd15c443e2c00a6fda8355231/gw2pois.cpp#L759

The game window class name is currently hardcoded into TacO when searching for the process.  The latest DX11 beta, when enabled, uses a different class name of `{ArenaNet_Gr_Window_Class}` meaning that TacO fails to detect the game when the beta is enabled.

Can either check for either one or can likely just see if it's not the patch window class name (`ArenaNet`).

**Comment by BoyC** [comment]
Fixed.
