### ISSUE TITLE
The realization principle of GW2TacO attaching route planning on the game screen

### ISSUE THREAD

**Issue by SuFIND** [BoyC/GW2TacO#138]
I recently encountered a path planning problem. When I watched [youtube](https://www.youtube.com/watch?v=I8I8KcalQqc), I saw someone else’s game path planning scheme. He attached the path to the game screen in advance, and it reminded me of playing Guild Wars 2 a few years ago. plug-in, I want to ask if I want to implement a plug-in like GW2TacO, what should I do?

**Comment by BoyC** [comment]
The game you want to extend this way needs some way of officially exposing the camera and the projection matrices like GW2 does. As for building an overlay, the source code of TacO is right here, you can try to adapt it to the game of your choice.

**Comment by SuFIND** [comment]
> The game you want to extend this way needs some way of officially exposing the camera and the projection matrices like GW2 does. As for building an overlay, the source code of TacO is right here, you can try to adapt it to the game of your choice.

really thank u
