### ISSUE TITLE
Map Icons Missing

### ISSUE THREAD

**Issue by ZomBieZAA** [BoyC/GW2TacO#14]
Seems as if the icons that taco shows are not showing on the 'large map', they are showing on minimap though. 

The trail from Tekkit's show though no icons on map.

**Comment by ZomBieZAA** [comment]
Also, once you open Taco it opens the map window, when you close the map window it does nothing

**Comment by BoyC** [comment]
Window toggling fixed.

**Comment by bcaddy** [comment]
I'm also having the issue with the markers not showing up on the big map.

**Comment by BoyC** [comment]
Fixed, release coming soon
