### ISSUE TITLE
Taco icon overlapping BLTC icon after Wizard's Vault addition

### ISSUE THREAD

**Issue by TheWhiteWolves** [BoyC/GW2TacO#141]
As can be seen below, since the addition of the Wizard's Vault the Taco icon is now overlapping the TP icon due to the new one shift things 1 to the right.

![image](https://github.com/BoyC/GW2TacO/assets/1471503/3fc841d3-39cc-41e4-a5aa-3f1f7ce1d4df)

**Comment by BoyC** [comment]
Thanks, I'm aware, will fix it in a couple days when I'm back home.

**Comment by TheWhiteWolves** [comment]
Closed by 023c432200ba8b48162de5a1ef61d097b9e93436
