### ISSUE TITLE
Map timer for GW2 - SotO maps

### ISSUE THREAD

**Issue by ScrambledBrain** [BoyC/GW2TacO#142]
Hi,

could you please add the new map timer for GW2 - SotO maps ?

Thanks in advance.

**Comment by Yoshi-to** [comment]
I tried to do them myself for now:

`<Map Name="Skywatch Archipelago" Length="120" Start="60" id="sam">
    <Event Name="Unlocking the Wizards Tower" Length="25" Color="d88860d7"/>
    <Event Name="" Length="95" Color="008AEAF4" />
  </Map>
  <Map Name="Amnytas" Length="120" Start="0" id="Amm">
    <Event Name="Defense of Amnytas" Color="d88860d7" Length="25"/>
    <Event Name="" Length="95" Color="008AEAF4" />
  </Map>`

You could add them to you maptimer.xml until they get officially implemented. The times seem to fit comapred with the Event Timers in the Wiki
The color may be odd, but i have no idea which color schema they follow

Hope it helps

**Comment by ScrambledBrain** [comment]
Thank you.
But I also a look on Blish HUD yesterday and with its major version 1.x.x it is quite stable and not much buggy anymore as it was before.
So, I switched to Blish HUD, because it is modularized and therefore has much more features than TacO.
Because more people working on it, there are also more updates, for example also on translations.
