### ISSUE TITLE
Question on IP adresses GW2TacO

### ISSUE THREAD

**Issue by Johan-p** [BoyC/GW2TacO#145]
If you throw GW2TacO.exe in virus total you end up with several hits on IP addresses it tries to contact.
Is this due to the fact that the code was build in Microsoft visual studio's or Is taco actually contacting servers for some of its functionality?
Most of the flagged IP addresses are all Microsoft and from what I can tell probably show up due to Microsoft application tracking.

https://www.virustotal.com/gui/file/dc099e1ffc0cd3ca8a1be1b8bd4e352ff4d7f4fc13ea5a28a8cacb1837c9e55f/relations

**Comment by BoyC** [comment]
Yes TacO opens some connections, for various purposes: 
1. it does a version check (but NEVER an auto update): https://github.com/BoyC/GW2TacO/blob/023c432200ba8b48162de5a1ef61d097b9e93436/GW2TacO.cpp#L586
2. it does an update of the marker packs: https://github.com/BoyC/GW2TacO/blob/023c432200ba8b48162de5a1ef61d097b9e93436/MarkerPack.cpp#L736
3. at various points it connects to the GW2 API: https://github.com/BoyC/GW2TacO/blob/023c432200ba8b48162de5a1ef61d097b9e93436/GW2API.cpp

Neither of these sites is hosted by me, and these connections aren't used for tracking in any shape or form (at least by me)
