### ISSUE TITLE
TacO doesn't exit with gw2 

### ISSUE THREAD

**Issue by bcaddy** [BoyC/GW2TacO#16]
I'm using the reactif distribution and updated by just replacing the `GW2TacO.exe` file.

Even with the proper option selected TacO doesn't exit when I exit gw2 and the TacO icon become non-interactable. After several minutes I just closed it with task manager

**Comment by bcaddy** [comment]
The issue isn't present with vanilla TacO so it's probably on Reactif's side. I'll close this issue and contact them

**Comment by bcaddy** [comment]
I'm wrong. It does occur with vanilla TacO. Sorry for the confusion

**Comment by bcaddy** [comment]
I've been testing this some more and I think I've nailed down the behavior. 

Vanilla TacO appear to properly shut down, in that the icon and overlay disappear. However, it's still running in Task Manager, using about 12% of my CPU and ~84MB of memory. When I next launch gw2 then vanilla TacO immediately reappears as if nothing had happened. Manually closing TacO either in the TacO menu or with task manager does actually close TacO.

TacO + Reactif definitely does not shut down properly when exiting gw2. The icon, trails, and markers are still visible but cannot be interacted with but it does become interactable again once you launch gw2 and start playing just like vanilla.

So it looks like both vanilla and reactif have the same underlying behavior of not closing properly, there's just something about the reactif distribution that make it continue showing the overlay

**Comment by BoyC** [comment]
Fixed, release coming soon

**Comment by bcaddy** [comment]
That did it. Thank you!
