### ISSUE TITLE
Crashing after having Taco open for a while

### ISSUE THREAD

**Issue by ZomBieZAA** [BoyC/GW2TacO#17]
Crash occurred at: 2021-09-22 13:25:16
Build version: GW2 TacO 050.2828r
Exception Type: c0000005
		d:\agent\_work\57\s\src\vctools\crt\vcruntime\src\string\i386\memcpy.asm (194)
		E:\!Code\GW2TacO\Bedrock\BaseLib\String.cpp (125)
		E:\!Code\GW2TacO\GW2API.cpp (31)
		E:\!Code\GW2TacO\MapTimer.cpp (32)
		C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.28.29333\include\Thread (44)
		minkernel\crts\ucrt\src\appcrt\startup\thread.cpp (97)
		Unresolved address: 767BFA29
		Unresolved address: 77C57A9E
		Unresolved address: 77C57A6E

**Comment by ZomBieZAA** [comment]
Seems as if this only happens when I have the timers on.

**Comment by BoyC** [comment]
Already fixed in a previous commit, the next release will have the fix.
