### ISSUE TITLE
Website SSL

### ISSUE THREAD

**Issue by wylel** [BoyC/GW2TacO#19]
I know this is not a priority right now with the latest patch woes, but wanted to put this in for the future. Most modern browsers throw up a big warning now (or force HTTPS all together) when a site is not serving over SSL. I know the site gw2taco.com is served on blogger, and you can enable HTTPS in the settings for the blog.

Here is the guide from Google on how to do this https://support.google.com/blogger/answer/6284029

I am not a developer, but this is something I can help with if needed for a walkthrough or whatever.

**Comment by BoyC** [comment]
Feels like I've set this up 5 times already. Looking into it.

**Comment by wylel** [comment]
It is doing it now. Could just be a blogger issue, as it would seem that Google has done all but abandon it.

**Comment by BoyC** [comment]
> It is doing it now. Could just be a blogger issue, as it would seem that Google has done all but abandon it.

Yeah at one point i'll need to migrate all that somewhere.
So I think this is fixed now, I left the http option there because of the way TacO is looking for the version update string, but https should work.
