### ISSUE TITLE
Is there a way to move the menu bar icon to its right?

### ISSUE THREAD

**Issue by lcdlyxrqy** [BoyC/GW2TacO#59]
First of all, let me make it clear that this might be a Chinese server specific issue so I'm not expecting there should be a workaround.
The Chinese server version of the game has extra icons in the menu bar which makes the gw2taco icon overlays with one existing icon. Is there anything I can do to move the icon? I used to manually change the InterfaceSize to 3 in the configuration file and it worked. But with the new version it seems to not work anymore.

**Comment by BoyC** [comment]
You can edit the .css files in order to move the menu button. It's the #MenuButton css tag.

**Comment by lcdlyxrqy** [comment]
Seems to have to change the values in #MenuHoverBox tag as well, or the icon may just vanish into the void.
Thanks anyway!
