### ISSUE TITLE
Application Hang Every 5 Seconds due to Teamspeak integration.

### ISSUE THREAD

**Issue by willjenkx** [BoyC/GW2TacO#61]
Versions
Teamspeak 3: 3.5.6
GW2 TacO: 051r

In TS3Connection.cpp:187 you have an infinite/busy loop that causes application hang for several seconds due to an error parsing the response from the Teamspeak application when you send the "whoami" command (TS3Connection.cpp:115) every 5 seconds.

**Comment by kay-el-zed** [comment]
Having the exact same issue. Only way to resolve this is by closing Teamspeak as the integration cannot be turned off. 

Teamspeak 3: 3.5.6
GW2 TacO: 051r
