### ISSUE TITLE
Position of TacO Icon wrong calculated

### ISSUE THREAD

**Issue by anolting** [BoyC/GW2TacO#62]
Hi  @BoyC 
I'm playing Gw2 on 4K monitor using the largest interface size.
With TacO latest version the icon ingame is unreachable as it is placed behind the the buttons for WvW and PvP. 

Please see the screenshot
![grafik](https://user-images.githubusercontent.com/12763750/135716630-c10d758a-0d71-4c34-9d9f-a5ea4e9e8e1e.png)

Best Alex

**Comment by BoyC** [comment]
Please try the -forcedpiaware command line option and let me know if that works.

**Comment by anolting** [comment]
Hi
it works with and without the option set. Strange. Anyway, thanks for you help.
