### ISSUE TITLE
Diamond marker randomly shows up

### ISSUE THREAD

**Issue by PaterFrog** [BoyC/GW2TacO#66]
![image](https://user-images.githubusercontent.com/46433636/145998605-a99cc73d-c140-4312-8d66-1dc144225410.png)
This marker shows up in multiple spots, and once it does, it won't disappear unless I turn off Tactical Markers entirely. (The same ones reappear once I toggle the markers on again.) This seems to happen mostly in the Mistlock Sanctuary, but I believe I've noticed it in the home instance, a city, and in the guild hall as well.

I have Tekkit's Guide installed, but this does not seem to be responsible - turning these off does _not_ make the markers disappear, but unchecking "Toggle Tactical Display" does.

I have deactivated all markers/guides except  for Tekkit's:
![image](https://user-images.githubusercontent.com/46433636/145998949-40071307-5dba-429e-911d-8cbef6314580.png)

I'm on DX9 (11 crashes my game on startup), Windows 10, my drivers are up-to-date, and my graphics card is a 2070 S. GW2 is in Windowed Fullscreen with DPI Scaling enabled.

**Comment by BoyC** [comment]
You're placing the marker yourself. Check the key bindings, it's set to + by default.

**Comment by PaterFrog** [comment]
Oooh, thanks. Didn't know that was a thing. XD

**Comment by BoyC** [comment]
It's the main purpose of TacO ;) The marker packs you're using were all created like that, someone placed the markers manually ;)

**Comment by PaterFrog** [comment]
Yes, I do know about that, but since I saw options with "editor" in them, I figured you had to manually enter editing mode or sth. I didn't realize the keybinds were  turned on and that this was all it took.
