### ISSUE TITLE
Crash on load with latest build

### ISSUE THREAD

**Issue by TheWhiteWolves** [BoyC/GW2TacO#67]
[crash.log](https://github.com/BoyC/GW2TacO/files/7714422/crash.log)

Looks like with the new build somethings been affected somewhere that causing an error on startup, it doesnt seem to hinder things too much as if you dont touch the error message taco is still working on the game, but will close if you click on the error.

**Comment by BoyC** [comment]
Note to self: Crash occurred when api was down, in the json parsing code due to malformed reply.
