### ISSUE TITLE
Slow refresh rate of the markups when having high FPS

### ISSUE THREAD

**Issue by jacksonwill0** [BoyC/GW2TacO#71]
while having  >30FPS the markups/paths will have a slow refresh rate (every 5sec) -> Taco is unusable then.

No difference between DX11 and normal is detected.
I am using a 144Hz Monitor, dont know if this will affect this.

**Comment by BoyC** [comment]
Could you please check with the latest build?

**Comment by jacksonwill0** [comment]
For the 54r it seems to be better. Some inaccurancy is sometime there but Taco is now usable again on higher FPS for me!
Much Thanks!

**Comment by BoyC** [comment]
Sadly the small single frame glitches can't be worked around unless TacO goes into a directx dll or the client exposes some way of syncing frames (not gonna happen), I did a lot of tweaking with the latest build to get it to be as optimal as possible for now.
