### ISSUE TITLE
Custom Markers Not Showing

### ISSUE THREAD

**Issue by Bwachtel** [BoyC/GW2TacO#72]
I created a custom marker package for my guild about a year ago. I went afk from the game for about 6 months until EOD dropped and when i went to open the custom marker package in taco it no longer shows? Was there a formatting change that i would need to update my file to match?

**Comment by BoyC** [comment]
The format didn't change. Does the log file say anything?

**Comment by Bwachtel** [comment]
![Data Location](https://user-images.githubusercontent.com/22524734/157793307-d2a2582c-5e85-4021-8921-6171a693e978.PNG)
![POI Location](https://user-images.githubusercontent.com/22524734/157793323-d95f6b70-5d5f-4cc4-acd3-4328bc8c5877.PNG)

**Comment by Bwachtel** [comment]
[GW2TacO.log](https://github.com/BoyC/GW2TacO/files/8228634/GW2TacO.log)

**Comment by Bwachtel** [comment]
![POI FIle](https://user-images.githubusercontent.com/22524734/157793549-739d07a6-a384-405a-b732-d10d179d31d5.PNG)

**Comment by Bwachtel** [comment]
Tried uploading the poi file but got an error, so there is a snippit of the begging of it.

So this file worked in taco previously and i havent changed anything since the last know working version of it. Any thoughts on whats going on?

**Comment by Bwachtel** [comment]
Well it works on my laptop, maybe the file is corrupt. Ill do some more troubleshooting.
