### ISSUE TITLE
Allow Alt/Ctrl/Shift to Modify Hotkey

### ISSUE THREAD

**Issue by SeparGW2** [BoyC/GW2TacO#78]
Allow keybinds to be set using Ctl/Alt/Shift prefix (e.g. Ctrl+Home)

**Comment by SeparGW2** [comment]
Ctrl added in recent update.  Alt and Shift not available for keybinds.

**Comment by BoyC** [comment]
Shift should work, Alt is problematic due to the nature of keyboard hooks.
