### ISSUE TITLE
Antivirus is flaging GW2TacO

### ISSUE THREAD

**Issue by montss** [BoyC/GW2TacO#83]
![Screenshot 2022-03-28 221858](https://user-images.githubusercontent.com/5758149/160470805-91164884-a1a0-4e5a-9f2c-b11c9dc094e8.png)
Starting with version 56, Bitdefender Total Security 26.0.12.56 is marking GW2TacO.exe as Gen:Variant:Razy.604973

**Comment by Technetium1** [comment]
@montss please submit an incorect detection report here https://www.bitdefender.com/consumer/support/answer/29358/
