### ISSUE TITLE
Taco not closing when GW closes

### ISSUE THREAD

**Issue by TheWhiteWolves** [BoyC/GW2TacO#85]
As can be seen in the below image the option is turned on but in the latest versions the program has not been closing when the game does.

![image](https://user-images.githubusercontent.com/1471503/161137789-0af616fa-ac4e-4513-895a-c50f27ce55ee.png)

**Comment by BoyC** [comment]
Thanks, will have a look at it.

**Comment by BoyC** [comment]
Will be fixed in the next build.
