### ISSUE TITLE
Resource nodes always shown in Frostgorge Sound

### ISSUE THREAD

**Issue by denchen** [BoyC/GW2TacO#86]
With everything off, the resource node icon still shows up on this map. I haven't seen this behavior on any other map.

Version: `061.3246rr`

![Screenshot 2022-04-02 19 42 12](https://user-images.githubusercontent.com/2073768/161409056-7e5f055b-8c15-4df5-a74b-a0dee460f5dd.png)

**Comment by BoyC** [comment]
Can you pack up your pois folder and the poidata.xml as well and send it to me please? These markers look to have reverted to ones that don't have any category, and that doesn't show up in the selection overlay, I'd like to know what happened here.

**Comment by denchen** [comment]
Let me know if that link doesn't work.

https://drive.google.com/file/d/1mrXFLXDwdOMQvQHCK7PQw2ZhovpHUR3k/view?usp=sharing

**Comment by BoyC** [comment]
Ty will check it asap

**Comment by BoyC** [comment]
It'll be fixed in the next build, but until then you can download the bundled .taco file from the repo directly and overwrite your local one with it to fix the issue (https://github.com/BoyC/GW2TacO/blob/main/POIs/TacOMarkers.taco)
