### ISSUE TITLE
TacO_062r 

### ISSUE THREAD

**Issue by motorhead018** [BoyC/GW2TacO#89]
@BoyC 
Not sure if this is just my setup that is having the problem or what. When I attempt to check or uncheck settings in the TacO menu ingame, the menu starts acting as if someone is holding down the refresh key and doesn't check/uncheck the setting.

I can share a screencap with you if necessary.

**Comment by BoyC** [comment]
Is it possible you have two instances of TacO running? Please check the task manager.

**Comment by motorhead018** [comment]
And this is why are you are awesome....I had three instances running..

**Comment by BoyC** [comment]
TacO should actually protect against that, did you run it with a -mumble parameter?
