### ISSUE TITLE
Version 062.3605r - Editor Problems/Suggestions

### ISSUE THREAD

**Issue by SeparGW2** [BoyC/GW2TacO#91]
Version 062.3605r

Problems

I have a dual screen setup.  I dragged the marker editor to my second screen, dropped it,  and it disappeared.  I can't find an xml file or registry entry that shows where window locations/sizes are stored.  I had bound the marker editor to a key and can still turn it on and off - I can select a marker and see the 3-axis indicator - but I cannot get to the  editor proper.  How can I get the editor screen back in the main window?

The debug text jitters much of the time. Sometimes it remains stable for a while, sometimes not.

When I select a marker, the header states: EDITED ITEM IS A MARKER! and marker data populates various fields in the editor.
If I click on an non-TacO item, the marker becomes deselected, but the header still shows EDITED ITEM IS A MARKER!

Whem I select a trail, the header states: EDITED ITEM IS A TRAIL! and trail data populates various fields in the editor.
If I click on an non-TacO item, the marker becomes deselected, and the header changes to EDITED ITEM IS A MARKER! even though no TacO item is selected.

Suggestions

When clicking on a trail or marker show the xml file it is in and the full text of its line in the file, or if the full text is not available, the line number in the file.  Due to some bad editing on my part, I have some markers that now show up as the default icon and no quick way to determine where they are in the xml files.

When an external (not in poidata.xml, I believe) marker or trail is selected the header should show it EDITED ITEM IS AN EXTERNAL MARKER! or EDITED ITEM IS AN EXTERNAL TRAIL! I still want to get info about the external items, even if I can't edit them.

I can copy the trail file and texture info from the editor (click on that text, Home, Ctrl+Shift+End, Ctrl+C) It would be helpful to have a copy button for each item.

**Comment by BoyC** [comment]
The issue with your suggestions is that the xml file doesn't exist while editing, there's no "line number" for it. There are ways to fix this though and I'll look into your issues.

**Comment by BoyC** [comment]
First: you can find the location of the window in the the tacoconfig.xml, those are the MarkerEditor_x1 x2 y1 y2 values. Delete those before starting TacO and the window will be back.

**Comment by BoyC** [comment]
Ok, so.
I suspect you did click on something when you had the deselect issue, but the ubertool was too far away and got z clipped so it didn't show. I expanded the far plane so that shouldn't happen anymore.
I added the id of the selected item to show on the marker editor so that should be enough to identify the marker you're editing.
I also made it so if an item is external it's shown both in the color of the label and the text.
As for a copy button for the text data... that'd be too much clutter, but you can always use the CTRL-A CTRL-C combo, that's what I do.
Fixes will be up in the next build.

**Comment by SeparGW2** [comment]
Adding a few more...
Version 062.3605r
Problems
 
The debug text jitters sideways some of the time, becoming illegible. Sometimes it remains stable for a while, sometimes not.

I have experienced multiple instances where the TacO interface vanishes in game, but it still shows in memory.  Also sometimes it stays open after GW2 is closed, even with 'Close when GW2 quits' selected.  Trails that were showing on the mini map remain visible on screen until I kill process.

Suggestions

Provide a global, adjustable, fadefar in the menu that overrides all markers and trails.  Some of the marker packs provide so many markers that that multitude far distant ones, especially if range is turned on, overwhelm the screen.  They are not really useful if they are that far away, but will likely be useful nearby.

Provide ability to specify text and background colors of each marker's info text.

On the Marker Editor what are Copied Text and Copy Message fields are for ?

On the small interface setting, to make the EDIT CATEGORY, MARKER TYPE, and DELETE SELECTED fully visible the marker editor window has to be quite wide.  Can the buttons be resized for 2 lines and smaller widths:
  EDIT     MARKER     DEL
CATGRY    TYPE       SLCTD

When you are even with a trail, it can effectively disappear since it has zero thickness.  Is there a way to give it "thickness" so it is visible from the side ?

**Comment by BoyC** [comment]
Please spread out your suggestions into separate tickets so they can be addressed individually after the new build has been released.
