### ISSUE TITLE
Info range unit is fixed in meters

### ISSUE THREAD

**Issue by SeparGW2** [BoyC/GW2TacO#92]
The info range scale appears to be always in meters unlike the other distance measurements which can be toggled between inches and meters.  An info range of 100 comes into view at 3940 units.

**Comment by BoyC** [comment]
Marker ranges are in engine units - which happens to be in meters.

**Comment by SeparGW2** [comment]
'Display Distances as Meters' is unchecked
If I put a TacO marker on a waypoint and move so the TacO POI distance shows as 100, the in game distance shows as 100.
If I set the marker's INFO RANGE to 100 and move to the edge of the UberTool circle the in game distance shows as 3,962 and the TacO POI distance shows as 3964. (see attached)
The units used for the INFO RANGE distance are different that the units used for non-meters display of TacO POI distances.

![Distance Check Section](https://user-images.githubusercontent.com/31021448/162557363-261f3c68-b6e9-4d49-a2bf-bf91106a8fb2.jpg)

**Comment by BoyC** [comment]
That may be 2 things: either a rounding error or that the distance is calculated in 2D in one app and 3D in the other and so the height difference could be a thing. Also, the waypoint is higher in the air then where you're placed under it, which could also account for this.
