### ISSUE TITLE
TacO Icon Not Appearing

### ISSUE THREAD

**Issue by MoFunk37** [BoyC/GW2TacO#96]
I've tried both windowed and windowed fullscreen modes but the TacO icon does not appear for me on the latest build. In order to exit TacO I have to use the Task Manager. I also can't adjust which markers I need to be visible as a result.

**Comment by C0WAL** [comment]
I'm using TacO in windowed fullscreen also. I can see the routes/nodes/event timer but I dont have the icon anywhere on my screen
![image](https://user-images.githubusercontent.com/62248766/162586865-a86abd6a-50aa-4cc7-af80-2e755d01e8b3.png)

**Comment by BoyC** [comment]
Working on it, it's got something to do with the non-larger css files, will be fixed in a bit.

**Comment by BoyC** [comment]
Check the latest release please.

**Comment by C0WAL** [comment]
> Check the latest release please.

Working fine for me now, thanks!
